
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'ASSOCIATION CARDINALITY CLASS_ID CLASS_NAME COMPOSITION_L COMPOSITION_LO COMPOSITION_R COMPOSITION_RO DOTDOT ERROR ID INSTANCE_ID NEWLINE NEW_TYPE NUMBER RELATION_ID aggregation boolean bringsAbout category characterization collective comparative complete componentOf composition const constitution creation date datetime derivation derived disjoint event externalDependence extrinsicMode formal functional_complexes functional_complexes general genset historicalDependence historicalRole historicalRoleMixin import inherence instantiation intrisicMode kind manifestation material mediation memberOf mixin mode number ordered package participation participational phase phaseMixin process quality quantity redefines relator role roleMixin situation specializes specifics string subCollectionOf subQualityOf subkind subsets termination time triggers value whereprograma : declaracao_pacotedeclaracao_pacote : package CLASS_ID'
    
_lr_action_items = {'package':([0,],[3,]),'$end':([1,2,4,],[0,-1,-2,]),'CLASS_ID':([3,],[4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'programa':([0,],[1,]),'declaracao_pacote':([0,],[2,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> programa","S'",1,None,None,None),
  ('programa -> declaracao_pacote','programa',1,'p_programa','analyser.py',5),
  ('declaracao_pacote -> package CLASS_ID','declaracao_pacote',2,'p_declaracao_pacote','analyser.py',10),
]
